### ISSUE TITLE
Normalized scRNA data available?

### ISSUE THREAD

**Issue by rcorbett-abcl** [Famingzhao/NEPAL#1]
Hi folks,
I was excited to see that you had collected together the available PCa scRNA datasets and accounted for batch effects.

Is the resulting expression matrix from your normalization available through the R package?    I see a data file called "NatMed.He.2021.Rds".  Do you have others available for the other scRNA datasets?

**Comment by Famingzhao** [comment]
Hi there,
Thank you for your interest in our research. Regarding your inquiry about the expression matrix of scRNA-seq datasets, I must mention that due to the large size of the original expression matrix, the R package currently only provides "NatMed.He.2021.Rds" and other bulk data as built-in test data. However, the single-cell data used in our study are sourced from publicly available datasets, and specific databases or publications are thoroughly listed in the manuscript.

If you encounter any bugs or have further questions regarding the NEPAL R package, please don't hesitate to reach out.

**Comment by rcorbett-abcl** [comment]
Great. Thanks for the great table with the GEO IDs and URLs for the public sets.   Have a good day!
